export const CONTACT_ME_REQUEST = 'CONTACT_ME_REQUEST'
export const CONTACT_ME_SUCCESS = 'CONTACT_ME_SUCCESS'
export const CONTACT_ME_FAIL = 'CONTACT_ME_FAIL'

export const API_KEY_REQUEST = 'API_KEY_REQUEST'
export const API_KEY_SUCCESS = 'API_KEY_SUCCESS'
export const API_KEY_FAIL = 'API_KEY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'